import type { Role } from "./roles";

export type Permission =
  | "VIEW_OWN_PROFILE"
  | "VIEW_MEDICAL_HISTORY"
  | "VIEW_ALLERGIES"
  | "VIEW_PRESCRIPTIONS"
  | "VIEW_LAB_REPORTS"
  | "VIEW_APPOINTMENTS"
  | "VIEW_MEDICAL_RECORDS"
  | "MANAGE_APPOINTMENTS"
  | "BOOK_APPOINTMENT"
  | "UPLOAD_REPORT"
  | "REQUEST_ACCESS"
  | "APPROVE_ACCESS"
  | "REVOKE_ACCESS"
  | "VIEW_ACCESS_LOG"
  | "CREATE_PRESCRIPTION"
  | "UPDATE_PRESCRIPTION"
  | "VIEW_PATIENTS"
  | "REVIEW_REPORT"
  | "REQUEST_LAB_TEST"
  | "UPDATE_ALLERGIES"
  | "ADD_DIAGNOSIS"
  | "ADD_MEDICAL_NOTE"
  | "VIEW_PATIENT_DETAILS"
  | "MANAGE_LAB_APPOINTMENTS"
  | "UPLOAD_LAB_REPORT"
  | "VIEW_PRESCRIPTIONS_FOR_DISPENSE"
  | "DISPENSE_PRESCRIPTION"
  | "VIEW_ORDERS"
  | "MANAGE_ORDERS";

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  PATIENT: [
    "VIEW_OWN_PROFILE",
    "VIEW_MEDICAL_HISTORY",
    "VIEW_ALLERGIES",
    "VIEW_PRESCRIPTIONS",
    "VIEW_LAB_REPORTS",
    "VIEW_APPOINTMENTS",
    "VIEW_MEDICAL_RECORDS",
    "MANAGE_APPOINTMENTS",
    "BOOK_APPOINTMENT",
    "UPLOAD_REPORT",
    "REQUEST_ACCESS",
    "APPROVE_ACCESS",
    "REVOKE_ACCESS",
    "VIEW_ACCESS_LOG",
  ],
  DOCTOR: [
    "VIEW_OWN_PROFILE",
    "VIEW_PATIENTS",
    "VIEW_PATIENT_DETAILS",
    "VIEW_APPOINTMENTS",
    "VIEW_PRESCRIPTIONS",
    "VIEW_LAB_REPORTS",
    "VIEW_MEDICAL_RECORDS",
    "VIEW_ALLERGIES",
    "CREATE_PRESCRIPTION",
    "UPDATE_PRESCRIPTION",
    "REVIEW_REPORT",
    "REQUEST_LAB_TEST",
    "UPDATE_ALLERGIES",
    "ADD_DIAGNOSIS",
    "ADD_MEDICAL_NOTE",
    "MANAGE_APPOINTMENTS",
  ],
  HOSPITAL: [
    "VIEW_OWN_PROFILE",
    "VIEW_PATIENTS",
    "VIEW_PATIENT_DETAILS",
    "VIEW_APPOINTMENTS",
    "VIEW_PRESCRIPTIONS",
    "VIEW_LAB_REPORTS",
    "VIEW_MEDICAL_RECORDS",
    "MANAGE_APPOINTMENTS",
  ],
  LAB: [
    "VIEW_OWN_PROFILE",
    "VIEW_APPOINTMENTS",
    "MANAGE_LAB_APPOINTMENTS",
    "VIEW_PRESCRIPTIONS",
    "UPLOAD_LAB_REPORT",
    "VIEW_LAB_REPORTS",
    "VIEW_PATIENT_DETAILS",
  ],
  PHARMACIST: [
    "VIEW_OWN_PROFILE",
    "VIEW_PRESCRIPTIONS_FOR_DISPENSE",
    "DISPENSE_PRESCRIPTION",
    "VIEW_ORDERS",
    "MANAGE_ORDERS",
  ],
};

export function hasPermission(role: Role, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}

export function canAccessPatient(role: Role): boolean {
  return ["DOCTOR", "HOSPITAL", "LAB", "PHARMACIST"].includes(role);
}
